GHA workflow: Add step to create or recreate the terraform external volumes for the CLI binary and providers used by the dev container

diff --git a/.github/workflows/wsl2.yml b/.github/workflows/wsl2.yml
--- a/.github/workflows/wsl2.yml
+++ b/.github/workflows/wsl2.yml
@@ -15,6 +15,18 @@ on:
         required: false
         type: string
         default: "ansible_ssh_keys_ansible"
+      terraform_volumes_recreate:
+        description: "Whether to recrate the ansible ssh_keys volume"
+        type: choice
+        options:
+          - 'true'
+          - 'false'
+        default: 'false'
+      terraform_cli_volume_name:
+        description: "The name of docker volume from which the Terraform CLI will be provided"
+        required: false
+        type: string
+        default: "terraform_cli"
       ansible_debug_mode:
           description: "Run Ansible with --check --diff"
           type: choice
@@ -83,6 +95,31 @@ jobs:
               docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml up --remove-orphans --detach
               # clean up stopped container but NOT the volumes
               docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml down --remove-orphans
+            fi
+          fi;
+          docker volume ls
+
+      - name: create_terraform_volumes
+        id: create_terraform_volumes
+        run: |
+          docker volume ls
+          # check volumes don't already exist
+          VOL=$(docker volume ls -f name=${{ inputs.terraform_cli_volume_name }} --format='{{.Name}}')
+          echo "VOL = $VOL"
+          if [ -z "$VOL" ]; then
+            echo "docker volume ${{ inputs.terraform_cli_volume_name }} does NOT exist ... creating"
+            docker compose -f ./terraform/docker-compose.yml up --remove-orphans --detach
+            # clean up stopped container but NOT the volumes
+            docker compose -f ./terraform/docker-compose.yml down --remove-orphans
+          else
+            echo "docker volume ${{ inputs.terraform_cli_volume_name }} already exists"
+            if [ ${{ inputs.terraform_volumes_recreate }} == 'true' ]; then
+              echo "re-creating the docker volume ${{ inputs.terraform_cli_volume_name }}"
+              # docker volume rm ${{ inputs.terraform_cli_volume_name }} || true
+              docker compose -f ./terraform/docker-compose.yml down --remove-orphans --volumes
+              docker compose -f ./terraform/docker-compose.yml up --remove-orphans --detach
+              # clean up stopped container but NOT the volumes
+              docker compose -f ./terraform/docker-compose.yml down --remove-orphans
             fi
           fi;
           docker volume ls
